name: enum4linux
title: Enum4Linux
base: core22
adopt-info: enum4linux

license: GPL-3.0-or-later
source-code: https://github.com/CiscoCXSecurity/enum4linux
issues: https://github.com/JitPatro/enum4linux-snap/issues

contact: https://github.com/JitPatro
summary: Enumerates info from Windows and Samba systems
description: |
  Enum4linux is a tool for enumerating information from Windows and Samba systems. It attempts to offer similar functionality to enum.exe formerly available from www.bindview.com.
  It is written in Perl and is basically a wrapper around the Samba tools smbclient, rpclient, net and nmblookup.
  The tool usage can be found in the below URL followed by examples, previous versions of the tool can be found at the bottom of that page.

  Features include:

   * RID Cycling (When RestrictAnonymous is set to 1 on Windows 2000)
   * User Listing (When RestrictAnonymous is set to 0 on Windows 2000)
   * Listing of Group Membership Information
   * Share Enumeration
   * Detecting if host is in a Workgroup or a Domain
   * Identifying the remote Operating System
   * Password Policy Retrieval (using polenum)

  More info: https://labs.portcullis.co.uk/tools/enum4linux/

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  enum4linux:
    command: bin/enum4linux
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      LD_LIBRARY_PATH: "$SNAP/usr/lib/samba:$LD_LIBRARY_PATH"
      PERL5LIB: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/:$SNAP/usr/share/perl/5.34/:$SNAP/usr/share/perl/5.34.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.34/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.34.0/"
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs: [home, network]
    
    
parts:
  samba:
    plugin: autotools
    source: https://download.samba.org/pub/samba/samba-latest.tar.gz
    autotools-configure-parameters:
      - --enable-fhs
      - --prefix=/usr
      - --sysconfdir=/etc
      - --localstatedir=/var/localstatedir
      - --with-configdir=/snap/enum4linux/current/etc
      - --with-piddir=/var/snap/enum4linux/common
      - --with-lockdir=/var/snap/enum4linux/common
      - --with-cachedir=/var/snap/enum4linux/common
      - --with-statedir=/var/snap/enum4linux/current
      - --with-socketpath=/var/snap/enum4linux/common
      - --with-privatedir=/var/snap/enum4linux/current
      - --with-sockets-dir=/var/snap/enum4linux/common
      - --with-privileged-socket-dir=/var/snap/enum4linux/common
      - --without-libarchive

    build-packages:
      - bison
      - build-essential
      - libgnutls28-dev
      - liblmdb-dev
      - libgpgme-dev
      - libparse-yapp-perl
      - libjansson-dev
      - libacl1-dev
      - libldap2-dev
      - libpam0g-dev
      - libtasn1-bin
      - libpopt-dev
      - libfl-dev
      - libdbus-1-dev
      - libkrb5-dev
      - libjson-perl
      - python3-markdown
      - python3-dnspython
      - python3-dev
      - zlib1g-dev
      
    stage-packages:
      - libjansson4

    override-build: |
      craftctl default
      mkdir -p "$CRAFT_PART_INSTALL"/etc; cp ./examples/smb.conf.default "$CRAFT_PART_INSTALL"/etc/smb.conf
      sed -i 's#\[global\]#\[global\]\n\nclient min protocol = CORE\n\nclient ipc signing = desired#g' "$CRAFT_PART_INSTALL"/etc/smb.conf

  enum4linux:
    after: [samba]
    plugin: nil
    source: https://github.com/CiscoCXSecurity/enum4linux.git
    stage-packages:
      - polenum
      - ldap-utils
      - perl
      - dnsutils

# the last two lines fix bugs in enum4linux itself.
    override-build: |
      craftctl set version=$(git describe --tags)
      mkdir -p "$CRAFT_PART_INSTALL"/usr/share/enum4linux
      mkdir -p "$CRAFT_PART_INSTALL"/bin
      sed -i "s/Usage: \$0/Usage: enum4linux/g" ./enum4linux.pl
      cp ./* "$CRAFT_PART_INSTALL"/usr/share/enum4linux/
      echo -e '#!/usr/bin/env sh \n\nset -e \n\ncd $SNAP/usr/share/enum4linux/ && exec ./enum4linux.pl "$@"' > "$CRAFT_PART_INSTALL"/bin/enum4linux
      chmod +x "$CRAFT_PART_INSTALL"/bin/enum4linux
      sed -i 's/\\s+\\.\\.\\s+D.*\\d/\\s+(\\.\\.|.*?)\\s+D.*\\d/g' "$CRAFT_PART_INSTALL"/usr/share/enum4linux/enum4linux.pl
      sed -i 's|$mapping_result="DENIED"; $listing_result="N/A";|$mapping_result="DENIED"; $listing_result="N/A";\n\t\t} elsif ($output =~ /NT_STATUS_NO_SUCH_FILE listing/) {\n\t\t\t$mapping_result="N/A"; $listing_result="N/A";|g' "$CRAFT_PART_INSTALL"/usr/share/enum4linux/enum4linux.pl
