name: enum4linux
title: Enum4Linux
base: core22
adopt-info: enum4linux

license: GPL-3.0-or-later
source-code: https://github.com/CiscoCXSecurity/enum4linux
issues: https://github.com/JitPatro/enum4linux-snap/issues

contact: https://github.com/JitPatro
summary: Enumerates info from Windows and Samba systems
description: |
  Enum4linux is a tool for enumerating information from Windows and Samba systems. It attempts to offer similar functionality to enum.exe formerly available from www.bindview.com.
  It is written in Perl and is basically a wrapper around the Samba tools smbclient, rpclient, net and nmblookup.
  The tool usage can be found in the below URL followed by examples, previous versions of the tool can be found at the bottom of that page.

  Features include:

   * RID Cycling (When RestrictAnonymous is set to 1 on Windows 2000)
   * User Listing (When RestrictAnonymous is set to 0 on Windows 2000)
   * Listing of Group Membership Information
   * Share Enumeration
   * Detecting if host is in a Workgroup or a Domain
   * Identifying the remote Operating System
   * Password Policy Retrieval (using polenum)

  More info: https://labs.portcullis.co.uk/tools/enum4linux/

icon: enum4linux.png

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  enum4linux:
    command: bin/enum4linux
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PERL5LIB: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/:$SNAP/usr/share/perl/5.34/:$SNAP/usr/share/perl/5.34.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.34/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.34.0/"
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs: [home, network]
    
layout:
  /etc/samba/smb.conf:
    bind-file: $SNAP/usr/share/samba/smb.conf

parts:
  enum4linux:
    plugin: nil
    source: https://github.com/CiscoCXSecurity/enum4linux.git
    stage-packages:
      - samba
      - smbclient
      - polenum
      - ldap-utils
      - perl
      - dnsutils

    organize:
      usr/lib/*-linux-gnu/samba/*: usr/lib/


    override-build: |
      snapcraftctl set-version $(git describe --tags)
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/usr/share/enum4linux
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/bin
      sed -i "s/Usage: \$0/Usage: enum4linux/g" ./enum4linux.pl
      cp ./* "$SNAPCRAFT_PART_INSTALL"/usr/share/enum4linux/
      echo -e '#!/usr/bin/env sh \n\nset -e \n\ncd $SNAP/usr/share/enum4linux/ && exec ./enum4linux.pl "$@"' > "$SNAPCRAFT_PART_INSTALL"/bin/enum4linux
      chmod +x "$SNAPCRAFT_PART_INSTALL"/bin/enum4linux
      sed -i 's#\[global\]#\[global\]\n\nclient min protocol = CORE#g' "$SNAPCRAFT_PART_INSTALL"/usr/share/samba/smb.conf
